// Comprehensive template configuration with styling and layout support

export const TEMPLATE_CONFIGS = {
  // Original templates
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional centered header with underline sections',
    category: 'Professional',
    layout: 'single-column',
    accentColor: '#003399',
    text: '#333333',
    textDark: '#000000',
    textMuted: '#555555',
    textLight: '#666666',
    border: '#cccccc',
    borderDark: '#000000',
    headerStyle: 'centered',
    sectionStyle: 'underline',
    bulletStyle: 'disc',
    nameSize: '22px',
    sectionTitleSize: '11px',
    borderWidth: '1px',
  },
  modern: {
    id: 'modern',
    name: 'Modern',
    description: 'Left-aligned with blue color bar sections',
    category: 'Contemporary',
    layout: 'single-column',
    accentColor: '#2563eb',
    text: '#374151',
    textDark: '#111827',
    textMuted: '#6b7280',
    textLight: '#9ca3af',
    border: '#e5e7eb',
    borderDark: '#2563eb',
    headerStyle: 'left',
    sectionStyle: 'colorbar',
    bulletStyle: 'arrow',
    nameSize: '26px',
    sectionTitleSize: '12px',
    borderWidth: '2px',
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    description: 'Centered header with boxed sections',
    category: 'Professional',
    layout: 'single-column',
    accentColor: '#059669',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#d1d5db',
    borderDark: '#1f2937',
    headerStyle: 'centered',
    sectionStyle: 'box',
    bulletStyle: 'dash',
    nameSize: '24px',
    sectionTitleSize: '11px',
    borderWidth: '1px',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean left-aligned with minimal decoration',
    category: 'Contemporary',
    layout: 'single-column',
    accentColor: '#18181b',
    text: '#18181b',
    textDark: '#09090b',
    textMuted: '#52525b',
    textLight: '#71717a',
    border: '#e4e4e7',
    borderDark: '#a1a1aa',
    headerStyle: 'left',
    sectionStyle: 'none',
    bulletStyle: 'disc',
    nameSize: '20px',
    sectionTitleSize: '10px',
    borderWidth: '0.5px',
  },

  // New Red Accent template
  redAccent: {
    id: 'redAccent',
    name: 'Red Accent',
    description: 'Bold red accent with modern styling',
    category: 'Creative',
    layout: 'single-column',
    accentColor: '#dc2626',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#f3f4f6',
    borderDark: '#dc2626',
    headerStyle: 'left',
    sectionStyle: 'colorbar',
    bulletStyle: 'arrow',
    nameSize: '26px',
    sectionTitleSize: '12px',
    borderWidth: '2px',
  },

  // New Purple Accent template
  purpleAccent: {
    id: 'purpleAccent',
    name: 'Purple Accent',
    description: 'Elegant purple with sophisticated layout',
    category: 'Creative',
    layout: 'single-column',
    accentColor: '#7c3aed',
    text: '#2d3748',
    textDark: '#1a202c',
    textMuted: '#4a5568',
    textLight: '#718096',
    border: '#e2e8f0',
    borderDark: '#7c3aed',
    headerStyle: 'centered',
    sectionStyle: 'colorbar',
    bulletStyle: 'dash',
    nameSize: '24px',
    sectionTitleSize: '12px',
    borderWidth: '1.5px',
  },

  // New Orange Compact Two-column layout
  orangeCompact: {
    id: 'orangeCompact',
    name: 'Orange Compact',
    description: 'Two-column layout with orange accent',
    category: 'Compact',
    layout: 'two-column',
    accentColor: '#f97316',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#e5e7eb',
    borderDark: '#f97316',
    headerStyle: 'left',
    sectionStyle: 'colorbar',
    bulletStyle: 'disc',
    nameSize: '20px',
    sectionTitleSize: '10px',
    borderWidth: '1px',
    sidebarWidth: '35%',
  },

  // New Teal Sidebar template
  tealSidebar: {
    id: 'tealSidebar',
    name: 'Teal Sidebar',
    description: 'Sidebar layout with teal accent',
    category: 'Sidebar',
    layout: 'sidebar',
    accentColor: '#0d9488',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#d1d5db',
    borderDark: '#0d9488',
    headerStyle: 'left',
    sectionStyle: 'box',
    bulletStyle: 'disc',
    nameSize: '22px',
    sectionTitleSize: '11px',
    borderWidth: '1px',
    sidebarWidth: '25%',
    sidebarBg: '#f3f4f6',
  },

  // New Indigo Two-column
  indigoModern: {
    id: 'indigoModern',
    name: 'Indigo Modern',
    description: 'Two-column with indigo accent',
    category: 'Compact',
    layout: 'two-column',
    accentColor: '#4f46e5',
    text: '#374151',
    textDark: '#111827',
    textMuted: '#6b7280',
    textLight: '#9ca3af',
    border: '#e5e7eb',
    borderDark: '#4f46e5',
    headerStyle: 'left',
    sectionStyle: 'colorbar',
    bulletStyle: 'arrow',
    nameSize: '22px',
    sectionTitleSize: '11px',
    borderWidth: '1.5px',
    sidebarWidth: '40%',
  },

  // New Slate Professional Sidebar
  slateSidebar: {
    id: 'slateSidebar',
    name: 'Slate Sidebar',
    description: 'Professional sidebar with slate tones',
    category: 'Sidebar',
    layout: 'sidebar',
    accentColor: '#475569',
    text: '#1e293b',
    textDark: '#0f172a',
    textMuted: '#475569',
    textLight: '#64748b',
    border: '#cbd5e1',
    borderDark: '#475569',
    headerStyle: 'left',
    sectionStyle: 'none',
    bulletStyle: 'dash',
    nameSize: '24px',
    sectionTitleSize: '11px',
    borderWidth: '0.5px',
    sidebarWidth: '28%',
    sidebarBg: '#f1f5f9',
  },

  // New Emerald Two-column Compact
  emeraldCompact: {
    id: 'emeraldCompact',
    name: 'Emerald Compact',
    description: 'Compact two-column with emerald accent',
    category: 'Compact',
    layout: 'two-column',
    accentColor: '#10b981',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#d1d5db',
    borderDark: '#10b981',
    headerStyle: 'left',
    sectionStyle: 'box',
    bulletStyle: 'disc',
    nameSize: '20px',
    sectionTitleSize: '10px',
    borderWidth: '1px',
    sidebarWidth: '35%',
  },

  // New Rose Professional
  roseModern: {
    id: 'roseModern',
    name: 'Rose Modern',
    description: 'Contemporary rose accent layout',
    category: 'Creative',
    layout: 'single-column',
    accentColor: '#e11d48',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#fce7f3',
    borderDark: '#e11d48',
    headerStyle: 'centered',
    sectionStyle: 'colorbar',
    bulletStyle: 'arrow',
    nameSize: '26px',
    sectionTitleSize: '12px',
    borderWidth: '2px',
  },

  // New Cyan Sidebar
  cyanSidebar: {
    id: 'cyanSidebar',
    name: 'Cyan Sidebar',
    description: 'Tech-focused sidebar with cyan accent',
    category: 'Sidebar',
    layout: 'sidebar',
    accentColor: '#06b6d4',
    text: '#0c4a6e',
    textDark: '#082f49',
    textMuted: '#164e63',
    textLight: '#06b6d4',
    border: '#cffafe',
    borderDark: '#06b6d4',
    headerStyle: 'left',
    sectionStyle: 'colorbar',
    bulletStyle: 'arrow',
    nameSize: '22px',
    sectionTitleSize: '11px',
    borderWidth: '1.5px',
    sidebarWidth: '30%',
    sidebarBg: '#ecf8ff',
  },

  // New Amber Two-column
  amberCompact: {
    id: 'amberCompact',
    name: 'Amber Compact',
    description: 'Warm two-column with amber accent',
    category: 'Compact',
    layout: 'two-column',
    accentColor: '#d97706',
    text: '#1f2937',
    textDark: '#111827',
    textMuted: '#4b5563',
    textLight: '#6b7280',
    border: '#fde68a',
    borderDark: '#d97706',
    headerStyle: 'left',
    sectionStyle: 'box',
    bulletStyle: 'dash',
    nameSize: '20px',
    sectionTitleSize: '10px',
    borderWidth: '1.5px',
    sidebarWidth: '38%',
  },
};

// Export as array for easy iteration
export const TEMPLATE_LIST = Object.values(TEMPLATE_CONFIGS);

// Group templates by category for UI organization
export const TEMPLATE_CATEGORIES = {
  Professional: TEMPLATE_LIST.filter(t => t.category === 'Professional'),
  Contemporary: TEMPLATE_LIST.filter(t => t.category === 'Contemporary'),
  Creative: TEMPLATE_LIST.filter(t => t.category === 'Creative'),
  Compact: TEMPLATE_LIST.filter(t => t.category === 'Compact'),
  Sidebar: TEMPLATE_LIST.filter(t => t.category === 'Sidebar'),
};
